### ISSUE TITLE
OMScripts submodule dependency

### ISSUE THREAD

**Issue by mpretty-cyro** [outware/storyboardcontroller#5]
It looks like this has an internal submodule included (https://github.com/outware/storyboardcontroller/blob/develop/.gitmodules) which is causing issues when trying to setup my CI as Carthage attempts to checkout the submodule and out CI doesn't have access to it.

**Comment by michaelloo** [comment]
Thanks for raising this issue! I've must have forgot to cleanup the leftovers of our old build tools.

PR #6 has been opened to address this issue.

Cheers!

**Comment by mpretty-cyro** [comment]
Hey @michaelloo, no worries and thanks for the quick turn-around!

**Comment by michaelloo** [comment]
@mpretty-cyro Hey mate, it should be fixed now, please have a go and let me know!

**Comment by mpretty-cyro** [comment]
@michaelloo Awesome thanks. I've pointed our Cartfile at the dev branch and it looks like it's working now - are you able to create a v1.0.3 release with this fix please?
