### ISSUE TITLE
Version 1.0.3 pointing at wrong commit

### ISSUE THREAD

**Issue by mpretty-cyro** [outware/storyboardcontroller#9]
Hey, sorry just a small one this time - it looks like the v1.0.3 release is pointing at the same commit as the v1.0.2 release.

**Comment by michaelloo** [comment]
Hi @mpretty-cyro, thanks for submitting an issue.

Apologies for this, should be fixed now! Please have a go.

**Comment by mpretty-cyro** [comment]
No worries, it's working now thanks.
